### ISSUE TITLE
More builds failing

### ISSUE THREAD

**Issue by ccjjmartin** [aquifer/aquifer#142]
## Description:
- Running `aquifer build` on D7 sites is failing with the latest version of aquifer
## Part 1 (config files):
- Updating aquifer requires the config files to be updated in old projects
## Error message:
- `aquifer build`

```
[TypeError: Cannot read property 'makeFile' of undefined]
```
## Current solution to part 1:
- Upgrade your aquifer.json file
## Part 2:
- Using a fresh site install `aquifer create test`
- Then running `aquifer build` results in:

```
aquifer build
Re-setting permissions...
Removing possible existing build...
Executing drush make...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn drush ENOENT
    at exports._errnoException (util.js:893:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)
    at node.js:405:3
```
## Versions:
- This message occurs using:
- `node --version` v5.11.1
- `drush --version` 8.1.2 and 7.3.0
- `aquifer -V` 1.0.0-beta1 (884504d)

**Comment by ccjjmartin** [comment]
## Solved:
- Drush was missing from my $PATH variable
- If anyone encounters this error in the future type `which drush`
- If nothing appears you need to add drush to your $PATH variable
- HINT: aliases DO NOT work (I was using aliases)

## To fix:
- `nano ~/.bash_profile`
- Add the location of the drush bin directory to your path, mine was in a subdirectory and looked like:

```
export PATH=$HOME/drush7/vendor/bin:$PATH
```
- Save the file and open a new shell window
