### ISSUE TITLE
Error when creating new aquifer project using beta1 for d8

### ISSUE THREAD

**Issue by haynescw** [aquifer/aquifer#158]
$ aquifer create beta_eight -d 8
(node:99289) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
TypeError: this.cli._events.hasOwnProperty is not a function
    at Promise (/usr/local/lib/node_modules/aquifer/lib/aquifer.api.js:133:33)
    at Aquifer.parse (/usr/local/lib/node_modules/aquifer/lib/aquifer.api.js:118:12)
    at Aquifer.initializeCli.then.then.then (/usr/local/lib/node_modules/aquifer/bin/aquifer.js:53:18)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:456:3

Im not really a node developer so im not sure how to debug this. When i tried to create a d8 project while having aquifer@1.0.0-beta1 installed, i got the above error.

If you need more information please let me know. Im trying to get a side by side comparison of this against BLT.

Thanks.

**Comment by chasingmaxwell** [comment]
@haynescw, wow. I'm sorry for being so late to respond to this. If you haven't already resolved this on your own and are still interested, it looks like you may have an old version of node. Could you try upgrading to something more recent, preferably 6.7.0? I recommend using [nvm](https://github.com/creationix/nvm) to manage installed versions of node because it makes it super easy to switch between different versions. While you're at it, you may as well get the latest and greatest aquifer as well, the latest beta is 1.0.0-beta3.

Thanks for checking out aquifer!
