### ISSUE TITLE
Re-vamp Aquifer path maps.

### ISSUE THREAD

**Issue by patrickocoffeyo** [aquifer/aquifer#93]
There are certain paths and folders in Aquifer that someone might not want to use, for instance `root`, or `drush` might never be useful for a project. We should make sure that some of these non-critical folders aren't required. As of now, they aren't explicitly required, but a very unhelpful critical error occurs when you _don't_ define them:

``` bash
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at new Project (/home/pcoffey/Projects/random/aquifer/lib/project.api.js:68:19)
    at Object.Init.setup (/home/pcoffey/Projects/random/aquifer/lib/init.api.js:32:27)
    at Object.<anonymous> (/home/pcoffey/Projects/random/aquifer/bin/aquifer.js:28:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
```
## So two things should happen:
- We should bump heads and decide which paths should be optional. These paths should be documented as such, and we should discuss whether or not they should exist in the default aquifer.json file. We still need to define these paths separately because the behaviors applied to files within these paths are specific, but perhaps there's a way to make a generic _this path_ ----goes to---> _this destination path_. It could look something like this:

``` javascript
{
...
  "paths": {
     ... all the required paths
  },
  "customPaths": {
    "drush": {
      "destination": "sites/all/drush",
      "excludePaths": ".gitkeep",
      "overrides": true
    },
    "root": {
      "destination": "/",
    }
  }
...
}
```
- If a required directory is _not_ specified in the aquifer.json file, we should always return a helpful error, like so:

``` bash
Property "drush" does not exist in the "paths" object in your aquifer.json file. This property is required for Aquifer to run correctly.
```

**Comment by patrickocoffeyo** [comment]
This functionality has been built! 👍
